myapp/urls.py
from django.urls import path
from . import views
from .views import home, agregar, detalle_pieza, listado_piezas, actualizar_datos, actualizar_img, eliminar_pieza, registro, suspender, editar_cuenta

urlpatterns =[
    path('', home, name="home"),
    path('agregar/', agregar, name="agregar"),
    path('pieza/<int:id>/', detalle_pieza, name='detalle_pieza'),
    path('listado-piezas/', listado_piezas, name="listado_piezas"),
    path('actualizar-img/<id>/', actualizar_img, name="actualizar_img"),
    path('actualizar-datos/<id>/', actualizar_datos, name='actualizar_datos'),
    path('eliminar-pieza/<id>/', eliminar_pieza, name='eliminar_pieza'),
    path('registro/', registro, name='registro'),
    path('pieza/suspender/<int:id>/', suspender, name='suspender'),
    path('editar_cuenta/', editar_cuenta, name='editar_cuenta'),
    path('translate/', views.translate_text, name='translate_text'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
       
    
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
from django.contrib.auth.models import AbstractUser
from datetime import date

opciones_pieza= [
    [0, "Busto"],
    [2, "Pintura"],
    [3, "Retrato"],
    [4, "Otro"]
]

opciones_ubicacion=[
    [0, "Salón Gabriela Mistral"],
    [1, "Hemeroteca"],
    [2, "Salón Medina"],
    [3, "Sala Ercilla"],
    [4, "Salón Camilo Henríquez"],
    [5, "Sector Alameda 1er piso"],
    [6, "Sector Alameda 2do piso"],
    [7, "Sector Moneda 1er piso"],
    [8, "Sector Moneda 2do piso"],

]
meses = [
        [1, 'Enero'],
        [2, 'Febrero'],
        [3, 'Marzo'],
        [4, 'Abril'],
        [5, 'Mayo'],
        [6, 'Junio'],
        [7, 'Julio'],
        [8, 'Agosto'],
        [9, 'Septiembre'],
        [10, 'Octubre'],
        [11, 'Noviembre'],
        [12, 'Diciembre'],
    ]
dias = [
    [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], 
    [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10'], 
    [11, '11'], [12, '12'], [13, '13'], [14, '14'], [15, '15'], 
    [16, '16'], [17, '17'], [18, '18'], [19, '19'], [20, '20'], 
    [21, '21'], [22, '22'], [23, '23'], [24, '24'], [25, '25'], 
    [26, '26'], [27, '27'], [28, '28'], [29, '29'], [30, '30'], 
    [31, '31']
]
class Agregar(models.Model):
    años = [(year, str(year)) for year in range(1000, date.today().year + 1)]
    #decir que tipo de dato estamos introduciendo 
    titulo= models.CharField(max_length=100) #CharField para strings o textos pequeños
    autor= models.CharField(max_length=30)
    ubicación= models.IntegerField(choices=opciones_ubicacion, null=True)
    pieza= models.IntegerField(choices= opciones_pieza, null=True)
    descripción= models.TextField(max_length=255) #TextField para textos largos
    año = models.IntegerField(choices=años, null=True, blank=True)
    mes = models.IntegerField(choices= meses, null=True, blank=True)
    día = models.IntegerField(choices= dias, null=True, blank=True)
    Imagen= models.ImageField(upload_to="imagenes", null=True)
    activo=models.BooleanField(default=True) #Campo para pausar información
    codigo_qr=models.ImageField(upload_to="qr_codes/", null=True)

    
    def __str__(self):
        return self.titulo

    

myapp/forms.py
from django import forms
from .models import Agregar
from datetime import date
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import PasswordInput



class AgregarForm(forms.ModelForm):
   
    class Meta:
        model = Agregar
        fields= ["titulo", "autor", "ubicación", "pieza", "descripción", "día", "mes", "año", "Imagen"]


class UpdateImg(forms.ModelForm):
    class Meta:
        model= Agregar
        fields= [ "Imagen"]

class UpdateForm(forms.ModelForm):
    class Meta:
        model= Agregar
        fields= ["titulo", "ubicación", "descripción", "día", "mes", "año"]

        

class CustomUserCreationForm(UserCreationForm): #creamos un form custom a partir del que django nos da Usercreationform
    email=forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name","email","password1", "password2"]

class UpdateCuenta(forms.ModelForm):
    password = forms.CharField(widget=PasswordInput(render_value=True),required=False)
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password"]
    widgets = {
            'password': forms.PasswordInput(render_value=True),
        }
    def clean_password(self):
        password = self.cleaned_data.get('password')
        if not password:
            return self.instance.password  # Retorna la contraseña actual si no se proporciona una nueva
        return password

myapp/views.py
from django.conf import settings
from googletrans import Translator
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
import qrcode
from datetime import date
from .forms import AgregarForm, UpdateImg, UpdateForm, CustomUserCreationForm, UpdateCuenta
from .models import Agregar
import os
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required, permission_required
from .decorators import user_iniciado
from django.core.paginator import Paginator
from django.http import Http404 

def home(request):
    query = request.GET.get('query')
    piezas = Agregar.objects.filter(activo=True)

    if query:
        piezas = piezas.filter(titulo__icontains=query)
    mensaje = "No se encontraron resultados para tu búsqueda." if query and not piezas.exists() else ""

    return render(request, 'myapp/home.html', {'piezas': piezas, 'query': query, 'mensaje': mensaje})

@permission_required('myapp.view_agregar')
@login_required(login_url="/accounts/login/")
def agregar(request):
    if request.method == 'POST':
        formulario = AgregarForm(request.POST, request.FILES)
        if formulario.is_valid():
            # Guardar nueva pieza
            nueva_pieza = formulario.save()
            
            # Generar URL y QR
            url_pieza = f"https://AdminQR.pythonanywhere.com/pieza/{nueva_pieza.id}/"
            qr_img = qrcode.make(url_pieza)
            qr_filename = f'qr_{nueva_pieza.id}.png'
            qr_path = os.path.join(settings.MEDIA_ROOT, 'qr_codes', qr_filename)
            qr_img.save(qr_path)
            
            # Actualizar la pieza con la ruta del QR
            nueva_pieza.codigo_qr = f"qr_codes/{qr_filename}"
            nueva_pieza.save()
            
            # Preparar datos para la vista QR
            qr_url = os.path.join(settings.MEDIA_URL, 'qr_codes', qr_filename)
            mensaje = "Guardado y QR generado con éxito"
            
            # Redirigir a la vista del QR generado
            return render(request, 'myapp/Pieza/qr_generado.html', {
                'qr_url': qr_url,
                'mensaje': mensaje,
            })
        else:
            # Si el formulario no es válido
            data = {'form': formulario}
            return render(request, 'myapp/Pieza/agregar.html', data)
    
    # Si la solicitud es GET
    data = {'form': AgregarForm()}
    return render(request, 'myapp/Pieza/agregar.html', data)
def detalle_pieza(request, id):
    pieza = get_object_or_404(Agregar, id=id)
    return render(request, 'myapp/detalle_pieza.html', {'pieza': pieza})

@permission_required('myapp.view_articulo')
@login_required(login_url="/accounts/login/")
def listado_piezas(request):
    elemento = Agregar.objects.all()
    page = request.GET.get('page', 1)

    try: 
        paginator = Paginator(elemento, 5)
        elemento= paginator.page(page)
    except:
        raise Http404
    
    data = {'entity': elemento,
            'paginator': paginator
            }
    return render(request, 'myapp/pieza_admin.html', data)

@permission_required('myapp.view_imagen')
@login_required(login_url="/accounts/login/")
def actualizar_img(request, id):
    pieza = get_object_or_404(Agregar, id=id)
    data = {'form': UpdateImg(instance=pieza)}
    if request.method == 'POST':
        nueva_img = Agregar.objects.get(id=id)
        formulario = UpdateImg(instance=pieza, data=request.FILES, files=request.FILES)
        if formulario.is_valid():
            nueva_img.Imagen.delete()
            formulario.save()
            return redirect(to="listado_piezas")
        data["form"] = formulario
    return render(request, 'myapp/Pieza/modificar.html', data)

@permission_required('myapp.view_articulo')
@login_required(login_url="/accounts/login/")
def actualizar_datos(request, id):
    pieza = get_object_or_404(Agregar, id=id)
    data = {'form': UpdateForm(instance=pieza)}
    if request.method == 'POST':
        formulario = UpdateForm(data=request.POST, instance=pieza, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            return redirect(to="listado_piezas")
        data["form"] = formulario
    return render(request, 'myapp/Pieza/modificar.html', data)

@permission_required('myapp.delete_articulo')
@login_required(login_url="/accounts/login/")
def eliminar_pieza(request, id):
    pieza = get_object_or_404(Agregar, id=id)
    img = Agregar.objects.get(id=id)
    if img.Imagen:
        img.Imagen.delete()
    qr_filename = f'qr_{id}.png'
    qr_path = os.path.join(settings.MEDIA_ROOT, 'qr_codes', qr_filename)
    if os.path.exists(qr_path):
        os.remove(qr_path)
    pieza.delete()
    return redirect(to="listado_piezas")

@user_iniciado
def registro(request):
    data = {'form': CustomUserCreationForm()}
    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            user = formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            email = formulario.cleaned_data['email']
            dominio_mail = email.split('@')[-1]
            group = Group.objects.get(name='Admin' if dominio_mail == 'usm.cl' else 'Usuario')
            user.groups.add(group)
            login(request, user)
            messages.success(request, "Te has registrado correctamente")
            return redirect(to="home")
        data["form"] = formulario
    return render(request, 'registration/registro.html', data)

def logoutUser(request):
    logout(request)
    return redirect(to='home')

@permission_required('myapp.view_articulo')
def suspender(request, id):
    pieza = get_object_or_404(Agregar, id=id)
    if request.method == 'POST':
        pieza.activo = not pieza.activo
        pieza.save()
        return redirect(to='listado_piezas')

@login_required(login_url="/accounts/login/")
def editar_cuenta(request):
    cuenta = request.user
    data = {'form': UpdateCuenta(instance=cuenta)}
    if request.method == 'POST':
        formulario = UpdateCuenta(data=request.POST, instance=cuenta, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            return redirect(to="home")
        data["form"] = formulario
    return render(request, 'myapp/editar_cuenta.html', data)

def translate_text(request):
    if request.method == "GET":
        text = request.GET.get('text', '')
        lang = request.GET.get('lang', 'es')
        translator = Translator()
        translated = translator.translate(text, dest=lang)
        return JsonResponse({"translated_text": translated.text})
    

myapp/templates/myapp/agregar.html
<form action="" class="agregar" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form }}

    <button type="submit" class="button">Enviar</button>
</form>

{% if mensaje %}
    <p>{{ mensaje }}</p>
{% endif %}

{% if qr_url %}
    <h3>Código QR generado:</h3>
    <img src="{{ qr_url }}" alt="Código QR">
{% endif %}

myapp/templates/myapp/detalle_pieza.html
<!DOCTYPE html>
{% load static %}
<html>

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <div id="google_translate_element" class="google-translate-container"></div>

    <style>
        .google-translate-container {
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 1000;
            background-color: #f8f9fa;
            border-radius: 8px;
            padding: 5px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }

        .goog-te-banner-frame {
            display: none !important; /* Ocultar el banner de Google */
        }

        /* Ajustar la lista desplegable de idiomas */
        .select.goog-te-combo {
            max-height: 300px; /* Establece un alto máximo */
            overflow-y: auto;  /* Permite scroll vertical */
        }
        .goog-te-combo {
            font-family: 'Roboto', sans-serif;
            font-size: 1rem;
            border-radius: 5px;
            padding: 0.5rem;
            border: 1px solid #ddd;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        
        }

        .goog-te-combo:hover {
            background-color: #e9ecef;
        }


        .card-title {
            font-family: 'Playfair Display', serif;
            font-size: 2.5rem; /* Tamaño destacado */
            font-weight: 700; /* Negrita moderada */
            letter-spacing: 0.5px; /* Espaciado ligero entre letras */
            color: #000000;
            text-align: center;
            text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.2);
            margin-top: 40px;
            margin-bottom: 40px;
        }

        .card-text {
            font-family: 'Roboto', sans-serif;
            font-size: 1.1rem;
            color: #34495e;
            line-height: 1.6;
        }

        .btn-custom {
            border-radius: 20px;
            padding: 0.5rem 1.5rem;
            font-weight: bold;
            transition: background-color 0.3s ease, box-shadow 0.3s ease;
        }

        .btn-primary-custom {
            background-color: #1abc9c;
            color: white;
            border: none;
        }
        .btn-danger-custom {
            background-color: #dc3545;
            color: white;
        }

        .btn-primary-custom:hover {
            background-color: #16a085;
            box-shadow: 0px 4px 8px rgba(26, 188, 156, 0.4);
        }

        .btn-secondary-custom {
            background-color: #95a5a6;
            color: white;
            border: none;
        }
        
        .btn-secondary-custom:hover {
            background-color: #7f8c8d;
            box-shadow: 0px 4px 8px rgba(149, 165, 166, 0.4);
        }
        .btn-danger-custom:hover {
            background-color: #dc3545;
            box-shadow: 0px 4px 8px rgba(146, 3, 3, 0.4);
            
        }
    </style>
    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({ pageLanguage: 'es', layout: google.translate.TranslateElement.InlineLayout.SIMPLE }, 'google_translate_element');
        }
    </script>
    <script type="text/javascript"
        src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
</head>

<body>

    <div class="container mt-5">
        <div class="card shadow-lg border-0 rounded">
            <div class="row g-0">
                <div class="col-md-5">
                    <img src="{{ pieza.Imagen.url }}" class="img-fluid rounded-start" alt="{{ pieza.titulo }}"
                        style="width: 100%; height: 100%; object-fit: cover;">
                </div>

                <div class="col-md-7">
                    <div class="card-body">
                        <h2 class="card-title">{{ pieza.titulo }}</h2>
                        <p class="card-text text-muted">{{ pieza.descripción }}</p>

                        <ul class="list-unstyled mt-3">
                            <li><strong>Autor:</strong> {{ pieza.autor }}</li>
                            <li><strong>Ubicación:</strong> {{ pieza.get_ubicación_display }}</li>
                            <li><strong>Tipo de pieza:</strong> {{ pieza.get_pieza_display }}</li>
                            <li><strong>Fecha:</strong> {% if pieza.día %}{{ pieza.día }}{% else %}-{% endif %}/{% if pieza.mes %}{{ pieza.get_mes_display }}{% else %}-{% endif %}/{% if pieza.año %}{{pieza.año }}{% else %}-{% endif %}</li>
                        </ul>
                        <div class="mt-4 d-flex flex-wrap gap-2">
                            {% if perms.myapp.view_agregar %}
                            <a href="{% url 'actualizar_img' pieza.id %}"
                                class="btn btn-primary-custom btn-custom">Editar Imagen</a>
                            <a href="{% url 'actualizar_datos' pieza.id %}"
                                class="btn btn-primary-custom btn-custom">Editar Información</a>
                                <form action="{% url 'suspender' pieza.id %}" method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-sm {% if pieza.activo %} btn btn-danger-custom{% else %}btn btn-success{% endif %}">
                                        {% if pieza.activo %}
                                            Suspender
                                        {% else %}
                                            Activar
                                        {% endif %}
                                    </button>
                                </form>
                            <a href="{% url 'listado_piezas' %}" class="btn btn-secondary-custom btn-custom">Volver al
                                listado</a>
                            {% endif %}
                            <a href="{% url 'home' %}" class="btn btn-secondary-custom btn-custom">Ir a la Página
                                Principal</a>
                            {% if perms.myapp.delete_agregar %}
                            
                            <button onclick="eliminar_pieza({{ pieza.id }})"
                                class="btn btn-danger-custom btn-custom">Eliminar Pieza</button>
                            {% endif %}
                        </div>
                        {% if perms.myapp.view_agregar and pieza.codigo_qr %}
                        <div class="mt-4 text-center">
                            <img src="{{ pieza.codigo_qr.url }}" class="img-thumbnail"
                                alt="Código QR de {{ pieza.titulo }}" style="width: 150px; height: 150px;">
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        function eliminar_pieza(id) {
            Swal.fire({
                title: "¿Estás seguro de querer eliminar {{ pieza.titulo }}?",
                text: "Esta acción no se puede deshacer",
                icon: "warning",
                showCancelButton: true,
                cancelButtonText: "No, cancelar",
                confirmButtonText: "Sí, eliminar",
                reverseButtons: true,
                confirmButtonColor: "#dc3545"
            }).then(function (result) {
                if (result.isConfirmed) {
                    window.location.href = "/eliminar-pieza/" + id + "/";
                }
            });
        }
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

myapp/templates/myapp/editar_cuenta.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-image: url("{% static 'images/2piso background.jpg' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            font-family: 'Arial', sans-serif;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh; /* Esto centra el contenido verticalmente en toda la pantalla */
        }

        .container {
            max-width: 500px;
            margin-top: 50px;
            background-color: rgba(255, 255, 255, 0.8);
            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
            padding: 20px 30px;
            border-radius: 10px;
        }

        h1 {
            font-family: 'Roboto', sans-serif;
            font-size: 2rem;
            font-weight: bold;
            color: #333333;
            text-align: center;
            margin-bottom: 20px;
        }

        .form-label {
            font-weight: bold;
            color: #555555;
        }

        .btn-primary {
            background-color: #333333;
            border: none;
            font-size: 16px;
            font-weight: bold;
            padding: 10px;
            border-radius: 8px;
            transition: all 0.3s ease;
        }

        .btn-primary:hover {
            background-color: #555555;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2);
        }

        .btn-secondary {
            background-color: #dddddd;
            border: none;
            color: #333333;
            font-weight: bold;
            padding: 10px;
            border-radius: 8px;
            text-decoration: none;
            transition: all 0.3s ease;
        }

        .btn-secondary:hover {
            background-color: #cccccc;
        }

        .password-toggle {
            margin-top: -40px;
            margin-left: 95%;
            cursor: pointer;
        }

        .text-center {
            text-align: center;
        }
    </style>
    <title>Editar Cuenta</title>
</head>

<body>
    <div class="container">
        <h1>Editar Cuenta</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                <a href="{% url 'home' %}" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>

    <script>
        function togglePassword() {
            const passwordField = document.getElementById("password");
            const type = passwordField.type === "password" ? "text" : "password";
            passwordField.type = type;
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

myapp/templates/myapp/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&display=swap" rel="stylesheet">
    <div id="google_translate_element" class="google-translate-container"></div>
    <style>
        .google-translate-container {
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 1000;
            background-color: #f8f9fa;
            border-radius: 8px;
            padding: 5px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }
        .goog-te-combo {
            font-family: 'Roboto', sans-serif;
            font-size: 1rem;
            border-radius: 5px;
            padding: 0.5rem;
            border: 1px solid #ddd;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .goog-te-combo:hover {
            background-color: #e9ecef;
        }

        .navbar {
            font-size: 1.6rem;
            padding: 1rem 1.5rem;
        }

        .navbar-brand {
            font-family: 'Playfair Display', serif;
            font-size: 36px;
            font-weight: bold;
            color: #333;
        }

        .navbar-brand:hover {
            text-decoration: none;
            color: #555;
        }

        .button-group {
            display: flex;
            justify-content: center;
            gap: 20px;
            margin-bottom: 30px;
        }

        .btn-custom {
            border-radius: 50px;
            padding: 10px 20px;
            background-color: #333333;
            color: white;
            font-size: 18px;
            padding: 0.5rem 1.5rem;
            transition: all 0.3s ease;
        }

        .btn-custom:hover {
            background-color: #555555;
        }

        .card {
            border: none;
            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);
            transition: transform 0.3s;
        }

        .card:hover {
            transform: scale(1.05);
        }

        .card-title {
            font-size: 1.5rem;
            font-weight: bold;
            text-align: center;
        }

        body {
            background-color: #b8b9b9;
        }

        .custom-toggler {
            width: 60px;
            height: 80px;
        }

        .navbar-toggler-icon {
            width: 60px;
            height: 60px;
        }

        @media (max-width: 768px) {

            /* Cambios para pantallas pequeñas */
            .navbar-toggler-icon {
                width: 50px;;
                height: 50px;
                

            }
            .custom-toggler {
                width: 70px;
                height: 60px;
            }
        }
    </style>
    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({pageLanguage: 'es', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
        }
    </script>
    <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
</head>

<body>
    <!-- Barra de navegación -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary" style="margin-top: 20px;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Admin Qr</a>
            <button class="navbar-toggler custom-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'home' %}">Home</a>
                    </li>
                    
                    {% if user.is_authenticated %}
                    {% if perms.myapp.view_agregar %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'listado_piezas' %}">Piezas</a>
                    </li>
                    {% endif %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            {{ user.first_name }} {{ user.last_name }}
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <form method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="dropdown-item">Cerrar sesión</button>
                                </form>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'editar_cuenta' %}">Editar cuenta</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'registro' %}">Registrarse</a>
                    </li>
                    {% endif %}
                </ul>
                <form class="d-flex" role="search" method="get" action="{% url 'home' %}">
                    <input class="form-control me-2" type="search" name="query" placeholder="Buscar pieza"
                        aria-label="Search" value="{{ request.GET.query }}">
                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                </form>
            </div>
        </div>
    </nav>

    <!-- Botones principales -->
    <div class="button-group mt-4 text-center">
        {% if perms.myapp.view_agregar %}
        <a href="{% url 'agregar' %}" class="btn btn-custom">Agregar Pieza</a>
        {% endif %}
        {% if perms.myapp.view_articulo %}
        <a href="{% url 'listado_piezas' %}" class="btn btn-custom">Listado piezas</a>
        {% endif %}
    </div>

    <!-- Listado de piezas -->
    <div class="container mt-5">
        <div class="row">
            {% if piezas %}
            {% for pieza in piezas %}
            {% if pieza.activo %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{{ pieza.Imagen.url }}" class="card-img-top" alt="{{ pieza.titulo }}"
                        style="height: 300px; object-fit: cover;">
                    <div class="card-body text-center">
                        <h5 class="card-title">{{ pieza.titulo }}</h5>
                        <a href="{% url 'detalle_pieza' pieza.id %}" class="btn btn-custom">Ver detalles</a>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
            {% else %}
            <div class="col-12 text-center">
                <p class="text-muted">No se encontraron piezas que coincidan con la búsqueda.</p>
            </div>
            {% endif %}
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>